import type { Metadata } from "next";
import { Overpass } from 'next/font/google'
import "@/app/assets/main.css";
import Header from "./layout/header";

const overpass = Overpass({
  subsets: ['latin'],
  variable: '--font-overpass',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={overpass.variable}>
        <Header />
        {children}
      </body>
    </html>
  );
}
